apiVersion: batch/v1
kind: Job
metadata:
  name: init-db
spec:
  template:
    spec:
      containers:
        - name: init-db
          image: postgres:16
          env:
          - name: PGPASSWORD
            value: "postgres"
          command: ["psql"]
          args: [
            "-h", "postgres-service",
            "-U", "postgres",
            "-d", "mydb",
            "-f", "/docker-entrypoint-initdb.d/init.sql"
          ]
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      restartPolicy: OnFailure
      volumes:
        - name: init-script
          configMap:
            name: init-sql-config
